# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    platform_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - l_joint1
      - l_joint2
      - l_joint3
      - l_joint4
      - l_joint5
      - l_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - r_joint1
      - r_joint2
      - r_joint3
      - r_joint4
      - r_joint5
      - r_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
platform_controller:
  ros__parameters:
    joint: platform_joint