left_arm_controller/rm_driver:
  ros__parameters:
    #robot param
    arm_ip: "169.254.128.18"        #设置TCP连接时的IP
    tcp_port: 8080                #设置TCP连接时的端口

    arm_type: "RM_75"             #机械臂型号设置 
    arm_dof: 7                    #机械臂自由度设置
    arm_joints: [l_joint1, l_joint2, l_joint3, l_joint4, l_joint5, l_joint6, l_joint7]

    udp_ip: "169.254.128.20"        #设置udp主动上报IP
    udp_cycle: 5                  #udp主动上报周期，需要是5的倍数。
    udp_port: 8089                #设置udp主动上报端口
    udp_force_coordinate: 0       #设置系统受力时六维力的基准坐标，0为传感器坐标系 1为当前工作坐标系 2为当前工具坐标系
