# MoveIt uses this configuration for controller management
controller_names:
  - left_arm_controller
  - right_arm_controller
  - platform_controller

left_arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - l_joint1
    - l_joint2
    - l_joint3
    - l_joint4
    - l_joint5
    - l_joint6
    - l_joint7
right_arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - r_joint1
    - r_joint2
    - r_joint3
    - r_joint4
    - r_joint5
    - r_joint6
    - r_joint7
platform_controller:
  type: GripperCommand
  joints:
    - platform_joint
  action_ns: gripper_cmd
  default: true